# Generated by Django 3.2 on 2021-04-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='thumbnail',
        ),
    ]
